name: Security Pipeline

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - master
      - features

    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-info:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Informations sur la PR
        run: |
          echo "Numéro PR : #${{ github.event.pull_request.number }}"
          echo "Titre : ${{ github.event.pull_request.title }}"
          echo "Branche source : ${{ github.head_ref }}"
          echo "Branche cible : ${{ github.base_ref }}"
          echo "Auteur PR : ${{ github.event.pull_request.user.login }}"
          echo "Est un brouillon : ${{ github.event.pull_request.draft }}"

  afficher-infos:
    runs-on: ubuntu-24.04

    steps:
      - name: Qui a déclenché ce workflow ?
        run: echo "Déclenché par ${{ github.actor }}"

      - name: Sur quelle branche ?
        run: 'echo "Branche :  ${{ github.ref_name }}"'

      - name: Quel événement ?
        run: 'echo "Événement : ${{ github.event_name }}"'

      - name: Quel commit ?
        run: 'echo "Commit SHA : ${{ github.sha }}"'

  gitleaks:
    needs: afficher-infos
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast:
    needs: afficher-infos
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Semgrep
        uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d
        with:
          config: p/security-audit

  sca:
    needs: afficher-infos
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln
          severity: CRITICAL,HIGH
          exit-code: '1'
          trivy-config: trivy.yaml

  generate-sbom:
    needs:
      - gitleaks
      - sast
      - sca

    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Generate and submit SBOM
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: fs
          format: github
          output: dependency-results.sbom.json
          scan-ref: .