-- Schéma de la plateforme de labs.
-- SQL standard compatible PostgreSQL et H2 (mode PostgreSQL), idempotent :
--   * exécuté par PostgreSQL à la création du volume (docker-entrypoint-initdb.d)
--   * rejoué sans effet par le backend au démarrage (spring.sql.init)

CREATE TABLE IF NOT EXISTS app_user (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(254) NOT NULL,
    password_hash           VARCHAR(255) NOT NULL,
    role                    VARCHAR(16)  NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    reset_token_hash        VARCHAR(64),
    reset_token_expires_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_app_user_email       UNIQUE (email),
    CONSTRAINT uk_app_user_reset_token UNIQUE (reset_token_hash),
    CONSTRAINT ck_app_user_role        CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS virtual_machine (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id          BIGINT       NOT NULL,
    operating_system  VARCHAR(16)  NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    host              VARCHAR(255),
    port              INTEGER,
    protocol          VARCHAR(8),
    access_username   VARCHAR(64),
    access_password   VARCHAR(128),
    started_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_vm_owner       FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_vm_owner_os    UNIQUE (owner_id, operating_system),
    CONSTRAINT ck_vm_os          CHECK (operating_system IN ('WINDOWS', 'LINUX')),
    CONSTRAINT ck_vm_protocol    CHECK (protocol IS NULL OR protocol IN ('RDP', 'SSH')),
    CONSTRAINT ck_vm_port        CHECK (port IS NULL OR port BETWEEN 1 AND 65535),
    -- Invariant du domaine : des accès existent si et seulement si la VM tourne.
    CONSTRAINT ck_vm_state CHECK (
        (status = 'RUNNING' AND host IS NOT NULL AND port IS NOT NULL AND protocol IS NOT NULL
            AND access_username IS NOT NULL AND access_password IS NOT NULL AND started_at IS NOT NULL)
        OR
        (status = 'STOPPED' AND host IS NULL AND port IS NULL AND protocol IS NULL
            AND access_username IS NULL AND access_password IS NULL AND started_at IS NULL)
    )
);

-- Accès VPN : le certificat client actuel de chaque utilisateur.
CREATE TABLE IF NOT EXISTS vpn_profile (
    user_id      BIGINT       PRIMARY KEY,
    common_name  VARCHAR(64)  NOT NULL,
    issued_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_vpn_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_vpn_cn   UNIQUE (common_name)
);

-- Catalogue de machines à compromettre. Les flags ne sont jamais stockés en
-- clair : seule leur empreinte SHA-256 est conservée (voir domain/box/Flag).
CREATE TABLE IF NOT EXISTS box (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(64)  NOT NULL,
    name              VARCHAR(64)  NOT NULL,
    operating_system  VARCHAR(16)  NOT NULL,
    difficulty        VARCHAR(16)  NOT NULL,
    synopsis          VARCHAR(512) NOT NULL,
    ip_address        VARCHAR(45)  NOT NULL,
    maker             VARCHAR(64)  NOT NULL,
    released_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    retired           BOOLEAN      NOT NULL DEFAULT FALSE,
    user_flag_hash    VARCHAR(64)  NOT NULL,
    root_flag_hash    VARCHAR(64)  NOT NULL,
    CONSTRAINT uk_box_slug       UNIQUE (slug),
    CONSTRAINT ck_box_os         CHECK (operating_system IN ('WINDOWS', 'LINUX')),
    CONSTRAINT ck_box_difficulty CHECK (difficulty IN ('VERY_EASY', 'EASY', 'MEDIUM', 'HARD', 'INSANE'))
);

-- Validation d'un flag par un joueur. L'unicité (joueur, machine, flag)
-- interdit de compter deux fois les mêmes points, même en cas de double
-- soumission simultanée.
CREATE TABLE IF NOT EXISTS box_own (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    box_id       BIGINT      NOT NULL,
    flag_kind    VARCHAR(8)  NOT NULL,
    points       INTEGER     NOT NULL,
    first_blood  BOOLEAN     NOT NULL DEFAULT FALSE,
    owned_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_own_user           FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_own_box            FOREIGN KEY (box_id)  REFERENCES box (id)      ON DELETE CASCADE,
    CONSTRAINT uk_own_user_box_kind  UNIQUE (user_id, box_id, flag_kind),
    CONSTRAINT ck_own_flag_kind      CHECK (flag_kind IN ('USER', 'ROOT')),
    CONSTRAINT ck_own_points         CHECK (points >= 0)
);

CREATE INDEX IF NOT EXISTS ix_box_own_user ON box_own (user_id);
CREATE INDEX IF NOT EXISTS ix_box_own_box  ON box_own (box_id, flag_kind);

-- Notation de la difficulté d'une machine par les joueurs. Le domaine
-- n'autorise le vote qu'une fois la machine possédée de bout en bout.
CREATE TABLE IF NOT EXISTS box_rating (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    box_id      BIGINT      NOT NULL,
    difficulty  VARCHAR(16) NOT NULL,
    rated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_rating_user       FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_rating_box        FOREIGN KEY (box_id)  REFERENCES box (id)      ON DELETE CASCADE,
    CONSTRAINT uk_rating_user_box   UNIQUE (user_id, box_id),
    CONSTRAINT ck_rating_difficulty CHECK (difficulty IN ('VERY_EASY', 'EASY', 'MEDIUM', 'HARD', 'INSANE'))
);

-- Cours, découpés en sections. Deux filières : forensique et défense.
CREATE TABLE IF NOT EXISTS course (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(64)  NOT NULL,
    title         VARCHAR(128) NOT NULL,
    track         VARCHAR(16)  NOT NULL,
    level         VARCHAR(16)  NOT NULL,
    summary       VARCHAR(512) NOT NULL,
    published_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_course_slug  UNIQUE (slug),
    CONSTRAINT ck_course_track CHECK (track IN ('FORENSICS', 'DEFENSE')),
    CONSTRAINT ck_course_level CHECK (level IN ('FUNDAMENTAL', 'EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE IF NOT EXISTS course_section (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id  BIGINT       NOT NULL,
    slug       VARCHAR(64)  NOT NULL,
    title      VARCHAR(128) NOT NULL,
    kind       VARCHAR(8)   NOT NULL,
    position   INTEGER      NOT NULL,
    minutes    INTEGER      NOT NULL,
    content    TEXT         NOT NULL,
    video_url  VARCHAR(512),
    CONSTRAINT fk_section_course     FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE,
    CONSTRAINT uk_section_course_slug UNIQUE (course_id, slug),
    CONSTRAINT ck_section_kind       CHECK (kind IN ('THEORY', 'LAB', 'QUIZ')),
    CONSTRAINT ck_section_position   CHECK (position >= 1),
    CONSTRAINT ck_section_minutes    CHECK (minutes >= 0)
);

-- Suivi de lecture : une ligne par section terminée.
CREATE TABLE IF NOT EXISTS course_section_completion (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    course_id     BIGINT NOT NULL,
    section_id    BIGINT NOT NULL,
    completed_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_completion_user    FOREIGN KEY (user_id)    REFERENCES app_user (id)      ON DELETE CASCADE,
    CONSTRAINT fk_completion_course  FOREIGN KEY (course_id)  REFERENCES course (id)        ON DELETE CASCADE,
    CONSTRAINT fk_completion_section FOREIGN KEY (section_id) REFERENCES course_section (id) ON DELETE CASCADE,
    CONSTRAINT uk_completion_user_section UNIQUE (user_id, section_id)
);

CREATE INDEX IF NOT EXISTS ix_course_section_course ON course_section (course_id);
CREATE INDEX IF NOT EXISTS ix_completion_user       ON course_section_completion (user_id);

-- Ajouts postérieurs à la création des tables, rejoués sans effet.
ALTER TABLE course_section ADD COLUMN IF NOT EXISTS video_url VARCHAR(512);

-- Cibles lancées à la demande : une ligne par couple (joueur, machine).
CREATE TABLE IF NOT EXISTS box_instance (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    box_id      BIGINT      NOT NULL,
    status      VARCHAR(16) NOT NULL,
    address     VARCHAR(45),
    started_at  TIMESTAMP WITH TIME ZONE,
    expires_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_instance_user     FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_instance_box      FOREIGN KEY (box_id)  REFERENCES box (id)      ON DELETE CASCADE,
    CONSTRAINT uk_instance_user_box UNIQUE (user_id, box_id),
    CONSTRAINT ck_instance_status   CHECK (status IN ('STOPPED', 'RUNNING')),
    -- Invariant du domaine : une instance démarrée a une adresse et une échéance.
    CONSTRAINT ck_instance_state CHECK (
        (status = 'RUNNING' AND address IS NOT NULL AND started_at IS NOT NULL AND expires_at IS NOT NULL)
        OR
        (status = 'STOPPED' AND address IS NULL AND started_at IS NULL AND expires_at IS NULL)
    )
);

-- Fichiers téléversés (vidéos de cours). Le contenu vit sur le stockage,
-- seule sa fiche est en base.
CREATE TABLE IF NOT EXISTS media_asset (
    id            VARCHAR(32)  PRIMARY KEY,
    filename      VARCHAR(128) NOT NULL,
    content_type  VARCHAR(64)  NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    uploaded_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    uploaded_by   BIGINT,
    CONSTRAINT fk_media_user  FOREIGN KEY (uploaded_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_media_size  CHECK (size_bytes > 0),
    CONSTRAINT ck_media_type  CHECK (content_type IN ('video/mp4', 'video/webm', 'video/ogg'))
);

-- Comptes rendus de compromission. Un par couple (auteur, machine).
CREATE TABLE IF NOT EXISTS writeup (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box_id      BIGINT       NOT NULL,
    author_id   BIGINT       NOT NULL,
    title       VARCHAR(128) NOT NULL,
    content     TEXT         NOT NULL,
    published   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_writeup_box       FOREIGN KEY (box_id)    REFERENCES box (id)      ON DELETE CASCADE,
    CONSTRAINT fk_writeup_author    FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_writeup_author_box UNIQUE (author_id, box_id)
);

CREATE INDEX IF NOT EXISTS ix_writeup_box ON writeup (box_id);

-- Quiz d'une section : questions et propositions. La bonne réponse est en
-- base, jamais dans la fiche du cours servie à l'apprenant.
CREATE TABLE IF NOT EXISTS quiz_question (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id  BIGINT       NOT NULL,
    statement   VARCHAR(512) NOT NULL,
    position    INTEGER      NOT NULL,
    CONSTRAINT fk_question_section  FOREIGN KEY (section_id) REFERENCES course_section (id) ON DELETE CASCADE,
    CONSTRAINT ck_question_position CHECK (position >= 1)
);

CREATE TABLE IF NOT EXISTS quiz_choice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id  BIGINT       NOT NULL,
    label        VARCHAR(256) NOT NULL,
    correct      BOOLEAN      NOT NULL DEFAULT FALSE,
    position     INTEGER      NOT NULL,
    CONSTRAINT fk_choice_question FOREIGN KEY (question_id) REFERENCES quiz_question (id) ON DELETE CASCADE,
    CONSTRAINT ck_choice_position CHECK (position >= 1)
);

CREATE INDEX IF NOT EXISTS ix_quiz_question_section ON quiz_question (section_id);
CREATE INDEX IF NOT EXISTS ix_quiz_choice_question  ON quiz_choice (question_id);

-- Abonnement d'un compte. Une ligne par compte abonné : un compte gratuit n'en
-- a pas, ce que le domaine traduit par Subscription.free().
CREATE TABLE IF NOT EXISTS subscription (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    plan        VARCHAR(16) NOT NULL,
    status      VARCHAR(16) NOT NULL,
    period      VARCHAR(16),
    started_at  TIMESTAMP WITH TIME ZONE,
    expires_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_subscription_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_subscription_user UNIQUE (user_id),
    CONSTRAINT ck_subscription_plan   CHECK (plan IN ('FREE', 'PRO')),
    CONSTRAINT ck_subscription_status CHECK (status IN ('ACTIVE', 'CANCELLED', 'EXPIRED'))
);

-- Paiements. Le montant est en unités indivisibles de sa devise (centimes pour
-- l'euro, francs entiers pour le XOF) : jamais un flottant, qui perdrait des
-- centimes. La référence est la nôtre et sert de clé d'idempotence face aux
-- notifications répétées des prestataires.
CREATE TABLE IF NOT EXISTS payment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(32)  NOT NULL,
    user_id             BIGINT       NOT NULL,
    period              VARCHAR(16)  NOT NULL,
    amount_minor        BIGINT       NOT NULL,
    currency            VARCHAR(3)   NOT NULL,
    method              VARCHAR(24)  NOT NULL,
    status              VARCHAR(16)  NOT NULL,
    provider_reference  VARCHAR(128),
    failure_reason      VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    settled_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_payment_user   FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_payment_reference UNIQUE (reference),
    CONSTRAINT ck_payment_amount CHECK (amount_minor > 0),
    CONSTRAINT ck_payment_period CHECK (period IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT ck_payment_method CHECK (method IN ('CARD', 'WAVE', 'ORANGE_MONEY')),
    CONSTRAINT ck_payment_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    -- Un paiement clos porte sa date de règlement, un paiement en attente non.
    CONSTRAINT ck_payment_settled CHECK ((status = 'PENDING') = (settled_at IS NULL))
);

CREATE INDEX IF NOT EXISTS ix_payment_user    ON payment (user_id);
CREATE INDEX IF NOT EXISTS ix_payment_settled ON payment (status, settled_at);

-- Machines réservées aux abonnés. Par défaut oui : une machine ajoutée sans
-- rien préciser ne se retrouve pas ouverte à tous par accident.
ALTER TABLE box ADD COLUMN IF NOT EXISTS pro_only BOOLEAN NOT NULL DEFAULT TRUE;

-- Journal des actes : en ajout seul, rien ne s'y modifie. Il sert au module
-- Events et alimente les indicateurs d'administration. La ressource concernée
-- est désignée par son lien (slug) et non par une clé étrangère : le journal
-- reste lisible après la suppression d'une machine ou d'un cours.
CREATE TABLE IF NOT EXISTS journal_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    kind        VARCHAR(32) NOT NULL,
    subject     VARCHAR(128),
    detail      VARCHAR(255),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_journal_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_journal_user     ON journal_event (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_journal_kind     ON journal_event (kind, occurred_at);
CREATE INDEX IF NOT EXISTS ix_journal_occurred ON journal_event (occurred_at DESC);

-- Assistance : une demande, et le fil de ses messages. Le fil part avec la
-- demande (ON DELETE CASCADE) : une conversation effacée ne laisse pas des
-- messages orphelins. Le statut est stocké, mais il est toujours déduit du
-- dernier message par le domaine — il est là pour que la file d'attente se
-- filtre en base plutôt qu'en mémoire.
CREATE TABLE IF NOT EXISTS support_ticket (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id  BIGINT       NOT NULL,
    category   VARCHAR(16)  NOT NULL,
    subject    VARCHAR(140) NOT NULL,
    status     VARCHAR(16)  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ticket_author FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_ticket_author ON support_ticket (author_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_ticket_status ON support_ticket (status, updated_at);

CREATE TABLE IF NOT EXISTS support_message (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT  NOT NULL,
    author_id BIGINT  NOT NULL,
    from_staff BOOLEAN NOT NULL,
    body      TEXT    NOT NULL,
    sent_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_message_ticket FOREIGN KEY (ticket_id) REFERENCES support_ticket (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_author FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_message_ticket ON support_message (ticket_id, sent_at);

-- Scénarios d'exercice : ils ordonnent ce qui existe déjà, machines et cours.
-- Aucun avancement n'est stocké : il se déduit des flags validés et des
-- sections terminées, de sorte qu'un joueur qui a fait le travail avant
-- d'ouvrir le scénario en voit les étapes déjà franchies.
CREATE TABLE IF NOT EXISTS scenario (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(64)  NOT NULL UNIQUE,
    title      VARCHAR(140) NOT NULL,
    brief      TEXT         NOT NULL,
    published  BOOLEAN      NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_scenario_published ON scenario (published, updated_at DESC);

-- La ressource visée est désignée par son lien (slug) et non par une clé
-- étrangère : un scénario reste lisible après la republication d'un cours, et
-- une ressource retirée se signale comme manquante au lieu de disparaître.
CREATE TABLE IF NOT EXISTS scenario_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT      NOT NULL,
    position    INTEGER     NOT NULL,
    kind        VARCHAR(16) NOT NULL,
    reference   VARCHAR(64) NOT NULL,
    instruction TEXT,
    objective   VARCHAR(16),
    CONSTRAINT fk_step_scenario FOREIGN KEY (scenario_id) REFERENCES scenario (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_step_scenario ON scenario_step (scenario_id, position);
