-- Schéma de la plateforme de labs.
-- SQL standard compatible PostgreSQL et H2 (mode PostgreSQL), idempotent :
--   * exécuté par PostgreSQL à la création du volume (docker-entrypoint-initdb.d)
--   * rejoué sans effet par le backend au démarrage (spring.sql.init)

CREATE TABLE IF NOT EXISTS app_user (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(254) NOT NULL,
    password_hash           VARCHAR(255) NOT NULL,
    role                    VARCHAR(16)  NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    reset_token_hash        VARCHAR(64),
    reset_token_expires_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_app_user_email       UNIQUE (email),
    CONSTRAINT uk_app_user_reset_token UNIQUE (reset_token_hash),
    CONSTRAINT ck_app_user_role        CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS virtual_machine (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id          BIGINT       NOT NULL,
    operating_system  VARCHAR(16)  NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    host              VARCHAR(255),
    port              INTEGER,
    protocol          VARCHAR(8),
    access_username   VARCHAR(64),
    access_password   VARCHAR(128),
    started_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_vm_owner       FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_vm_owner_os    UNIQUE (owner_id, operating_system),
    CONSTRAINT ck_vm_os          CHECK (operating_system IN ('WINDOWS', 'LINUX')),
    CONSTRAINT ck_vm_protocol    CHECK (protocol IS NULL OR protocol IN ('RDP', 'SSH')),
    CONSTRAINT ck_vm_port        CHECK (port IS NULL OR port BETWEEN 1 AND 65535),
    -- Invariant du domaine : des accès existent si et seulement si la VM tourne.
    CONSTRAINT ck_vm_state CHECK (
        (status = 'RUNNING' AND host IS NOT NULL AND port IS NOT NULL AND protocol IS NOT NULL
            AND access_username IS NOT NULL AND access_password IS NOT NULL AND started_at IS NOT NULL)
        OR
        (status = 'STOPPED' AND host IS NULL AND port IS NULL AND protocol IS NULL
            AND access_username IS NULL AND access_password IS NULL AND started_at IS NULL)
    )
);

-- Accès VPN : le certificat client actuel de chaque utilisateur.
CREATE TABLE IF NOT EXISTS vpn_profile (
    user_id      BIGINT       PRIMARY KEY,
    common_name  VARCHAR(64)  NOT NULL,
    issued_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_vpn_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_vpn_cn   UNIQUE (common_name)
);

-- Catalogue de machines à compromettre. Les flags ne sont jamais stockés en
-- clair : seule leur empreinte SHA-256 est conservée (voir domain/box/Flag).
CREATE TABLE IF NOT EXISTS box (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(64)  NOT NULL,
    name              VARCHAR(64)  NOT NULL,
    operating_system  VARCHAR(16)  NOT NULL,
    difficulty        VARCHAR(16)  NOT NULL,
    synopsis          VARCHAR(512) NOT NULL,
    ip_address        VARCHAR(45)  NOT NULL,
    maker             VARCHAR(64)  NOT NULL,
    released_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    retired           BOOLEAN      NOT NULL DEFAULT FALSE,
    user_flag_hash    VARCHAR(64)  NOT NULL,
    root_flag_hash    VARCHAR(64)  NOT NULL,
    CONSTRAINT uk_box_slug       UNIQUE (slug),
    CONSTRAINT ck_box_os         CHECK (operating_system IN ('WINDOWS', 'LINUX')),
    CONSTRAINT ck_box_difficulty CHECK (difficulty IN ('VERY_EASY', 'EASY', 'MEDIUM', 'HARD', 'INSANE'))
);

-- Validation d'un flag par un joueur. L'unicité (joueur, machine, flag)
-- interdit de compter deux fois les mêmes points, même en cas de double
-- soumission simultanée.
CREATE TABLE IF NOT EXISTS box_own (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    box_id       BIGINT      NOT NULL,
    flag_kind    VARCHAR(8)  NOT NULL,
    points       INTEGER     NOT NULL,
    first_blood  BOOLEAN     NOT NULL DEFAULT FALSE,
    owned_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_own_user           FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_own_box            FOREIGN KEY (box_id)  REFERENCES box (id)      ON DELETE CASCADE,
    CONSTRAINT uk_own_user_box_kind  UNIQUE (user_id, box_id, flag_kind),
    CONSTRAINT ck_own_flag_kind      CHECK (flag_kind IN ('USER', 'ROOT')),
    CONSTRAINT ck_own_points         CHECK (points >= 0)
);

CREATE INDEX IF NOT EXISTS ix_box_own_user ON box_own (user_id);
CREATE INDEX IF NOT EXISTS ix_box_own_box  ON box_own (box_id, flag_kind);

-- Notation de la difficulté d'une machine par les joueurs. Le domaine
-- n'autorise le vote qu'une fois la machine possédée de bout en bout.
CREATE TABLE IF NOT EXISTS box_rating (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    box_id      BIGINT      NOT NULL,
    difficulty  VARCHAR(16) NOT NULL,
    rated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_rating_user       FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_rating_box        FOREIGN KEY (box_id)  REFERENCES box (id)      ON DELETE CASCADE,
    CONSTRAINT uk_rating_user_box   UNIQUE (user_id, box_id),
    CONSTRAINT ck_rating_difficulty CHECK (difficulty IN ('VERY_EASY', 'EASY', 'MEDIUM', 'HARD', 'INSANE'))
);

-- Cours, découpés en sections. Deux filières : forensique et défense.
CREATE TABLE IF NOT EXISTS course (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(64)  NOT NULL,
    title         VARCHAR(128) NOT NULL,
    track         VARCHAR(16)  NOT NULL,
    level         VARCHAR(16)  NOT NULL,
    summary       VARCHAR(512) NOT NULL,
    published_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_course_slug  UNIQUE (slug),
    CONSTRAINT ck_course_track CHECK (track IN ('FORENSICS', 'DEFENSE')),
    CONSTRAINT ck_course_level CHECK (level IN ('FUNDAMENTAL', 'EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE IF NOT EXISTS course_section (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id  BIGINT       NOT NULL,
    slug       VARCHAR(64)  NOT NULL,
    title      VARCHAR(128) NOT NULL,
    kind       VARCHAR(8)   NOT NULL,
    position   INTEGER      NOT NULL,
    minutes    INTEGER      NOT NULL,
    content    TEXT         NOT NULL,
    CONSTRAINT fk_section_course     FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE,
    CONSTRAINT uk_section_course_slug UNIQUE (course_id, slug),
    CONSTRAINT ck_section_kind       CHECK (kind IN ('THEORY', 'LAB', 'QUIZ')),
    CONSTRAINT ck_section_position   CHECK (position >= 1),
    CONSTRAINT ck_section_minutes    CHECK (minutes >= 0)
);

-- Suivi de lecture : une ligne par section terminée.
CREATE TABLE IF NOT EXISTS course_section_completion (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    course_id     BIGINT NOT NULL,
    section_id    BIGINT NOT NULL,
    completed_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_completion_user    FOREIGN KEY (user_id)    REFERENCES app_user (id)      ON DELETE CASCADE,
    CONSTRAINT fk_completion_course  FOREIGN KEY (course_id)  REFERENCES course (id)        ON DELETE CASCADE,
    CONSTRAINT fk_completion_section FOREIGN KEY (section_id) REFERENCES course_section (id) ON DELETE CASCADE,
    CONSTRAINT uk_completion_user_section UNIQUE (user_id, section_id)
);

CREATE INDEX IF NOT EXISTS ix_course_section_course ON course_section (course_id);
CREATE INDEX IF NOT EXISTS ix_completion_user       ON course_section_completion (user_id);
